// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Tasks.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TaskModel_Task_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaskModel_Task_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201402140854281_TaskModel_Task_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
